# Generated by Django 5.0.4 on 2024-05-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=70)),
                ('category', models.CharField(default=0, max_length=70)),
                ('subcategory', models.CharField(default=0, max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images/images')),
            ],
        ),
    ]
