# Generated by Django 5.0.4 on 2024-05-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_auth', '0003_orders_orderupdate_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='item_json',
            new_name='items_json',
        ),
    ]
