# Generated by Django 5.1 on 2024-12-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_auth', '0004_rename_item_json_orders_items_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='size',
            field=models.CharField(default='', max_length=50),
        ),
    ]
